[workspace]
resolver = "2"
members = [
    "crates/datawal-core",
]

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/deepcausa/datawal"
homepage = "https://github.com/deepcausa/datawal"
rust-version = "1.75"

[workspace.dependencies]
anyhow = "1"
crc32c = "0.6"
fs2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
safeatomic-rs = "0.1"
tempfile = "3"
